
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_ null
  spring:
    flyway:
      locations: sql


#jwt:
#  secret: 2c57cf3a-c804-4dc5-8cd4-93b8d8581948
#  expiration: 999999